"""add cta fields

Revision ID: 381c0f261c42
Revises: a2aa86bb6ac7
Create Date: 2026-07-20 05:20:41.077349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381c0f261c42'
down_revision = 'a2aa86bb6ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cta_subtitle', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cta_button_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cta_button_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_column('cta_button_link')
        batch_op.drop_column('cta_button_text')
        batch_op.drop_column('cta_subtitle')
        batch_op.drop_column('cta_title')

    # ### end Alembic commands ###
