"""add customers_rows and selected_clients to home_config

Revision ID: 3825edfcbdb7
Revises: 
Create Date: 2026-05-20 14:38:57.114846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3825edfcbdb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customers_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('selected_clients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.drop_column('selected_clients')
        batch_op.drop_column('customers_rows')

    # ### end Alembic commands ###
