"""add google_map_embed and social media fields to company_info

Revision ID: 7e86f59f6c72
Revises: 3825edfcbdb7
Create Date: 2026-05-20 15:44:13.253583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e86f59f6c72'
down_revision = '3825edfcbdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_map_embed', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('show_facebook', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('line_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('show_line', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('show_instagram', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_column('show_instagram')
        batch_op.drop_column('instagram')
        batch_op.drop_column('show_line')
        batch_op.drop_column('line_id')
        batch_op.drop_column('show_facebook')
        batch_op.drop_column('facebook')
        batch_op.drop_column('google_map_embed')

    # ### end Alembic commands ###
