"""add office_hours

Revision ID: 8268c2654ba3
Revises: f601cc5ff087
Create Date: 2026-07-20 04:41:03.478741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8268c2654ba3'
down_revision = 'f601cc5ff087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_hours', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_column('office_hours')

    # ### end Alembic commands ###
