"""add footer_name

Revision ID: a2aa86bb6ac7
Revises: 8268c2654ba3
Create Date: 2026-07-20 04:57:49.641296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2aa86bb6ac7'
down_revision = '8268c2654ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('footer_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_column('footer_name')

    # ### end Alembic commands ###
