"""Add updated_at to blog, create blog_edit_history, remove date field

Revision ID: f601cc5ff087
Revises: 7e86f59f6c72
Create Date: 2026-05-28 02:02:14.885142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f601cc5ff087'
down_revision = '7e86f59f6c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('edited_by', sa.String(length=100), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('fields_changed', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_column('updated_at')

    op.drop_table('blog_edit_history')
    # ### end Alembic commands ###
